### ISSUE TITLE
unable to open database file

### ISSUE THREAD

**Issue by karthikkunala** [datasets/covid-19#7] opened 2020-03-12 10:59 UTC
Hi,
When I try to run in Jupyter notebook, am getting error as unable to open database file.

OperationalError: unable to open database file

**Comment by SavoX2** [comment] 2020-03-20 19:04
Any update on this?

**Comment by eemberda** [comment] 2020-03-21 02:58
I also encountered the same:
Traceback (most recent call last):
  File "process.py", line 39, in <module>
    'aggregate': 'first'
  File "C:\ProgramData\Anaconda3\lib\site-packages\dataflows\processors\join.py", line 363, in join
    return join_aux(source_name, source_key, source_delete, target_name, target_key, fields, full, mode)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dataflows\processors\join.py", line 172, in join_aux
    db_keys_usage = KVFile()
  File "C:\ProgramData\Anaconda3\lib\site-packages\kvfile\kvfile.py", line 19, in __init__
    self.db = DB_ENGINE.connect(self.tmpfile.name)
sqlite3.OperationalError: unable to open database file

**Comment by SavoX2** [comment] 2020-03-21 14:24
@zelima it would appear multiple people have this same exact problem? Is there a solution for it?

**Comment by zelima** [comment] 2020-03-22 04:17
@karthikkunala are you also using windows?

I have no idea, but after googling a bit it might be related to insufficient permission for sqlite. See https://github.com/gunthercox/ChatterBot/issues/1044#issuecomment-340230752 also https://serverfault.com/a/57597

> Usually sqlite db file will created in current directory. Due to lack of permission sqlite unable to create db.sqlite3 file on your current directory.

**Comment by rufuspollock** [comment] 2020-03-22 15:34
@karthikkunala can you give more detail of how you are trying to use this?

**Comment by odev954** [comment] 2020-03-23 20:21
Hi,
I just opened up the project, and after I run the code 'process.py'  I received the same error.
Here is my traceback:
Traceback (most recent call last):
  File "C:\Users\user\Desktop\covid-19\process.py", line 44, in <module>
    'aggregate': 'first'
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\dataflows\processors\join.py", line 363, in join
    return join_aux(source_name, source_key, source_delete, target_name, target_key, fields, full, mode)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\dataflows\processors\join.py", line 172, in join_aux
    db_keys_usage = KVFile()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\kvfile\kvfile.py", line 19, in __init__
    self.db = DB_ENGINE.connect(self.tmpfile.name)
sqlite3.OperationalError: unable to open database file

**Comment by odev954** [comment] 2020-03-23 20:29
It's made the program crash every time I tried to run it.

**Comment by rufuspollock** [comment] 2020-03-23 22:20
@odev954 why are you trying to run it? That's the data collection script.

**Comment by odev954** [comment] 2020-03-24 08:47
![Capture](https://user-images.githubusercontent.com/55921680/77405850-6db3ca80-6dbc-11ea-8474-646bf3a6b6f2.PNG)

**Comment by anuveyatsu** [comment] 2020-03-24 15:01
@karthikkunala @SavoX2 @eemberda @odev954 hi all, can you try to follow updated instructions - https://github.com/datasets/covid-19#preparation ? Also, make sure you're using python v3.6 or newer.

**Comment by odev954** [comment] 2020-03-24 15:21
I followed the updated preparation instructions but I still got the same error as before after I run the 'process.py' script. I am currently running it in python v3.6.8 on Windows 10.
Here is the traceback I received:
`Traceback (most recent call last):
  File "process.py", line 44, in <module>
    'aggregate': 'first'
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\dataflows\processors\join.py", line 363, in join
    return join_aux(source_name, source_key, source_delete, target_name, target_key, fields, full, mode)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\dataflows\processors\join.py", line 172, in join_aux
    db_keys_usage = KVFile()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\kvfile\kvfile.py", line 19, in __init__
    self.db = DB_ENGINE.connect(self.tmpfile.name)
sqlite3.OperationalError: unable to open database file`

**Comment by odev954** [comment] 2020-03-24 20:10
after I run the project on my VM (OS: Ubunto) the project is working and the process.py is running successfully, maybe it's because the 'dataflows' package is not so supported currently in Windows or has some issues.

**Comment by navmedvideos** [comment] 2020-03-26 10:29
Coronavirus Live Stream - Real-time counter, Maps, and worldwide stats.

https://www.youtube.com/watch?v=qTbR2UKTQQc

**Comment by midhunxavier** [comment] 2020-03-26 12:40
I'm also getting the same error. I have followed the instructions and using python version greater 3.6 on windows machine.

Traceback (most recent call last):
  File ".\scripts\process.py", line 90, in <module>
    join(
  File "C:\Users\midhu\Documents\midhun\covid 19 projects\envs\covid19_1_env\lib\site-packages\dataflows\processors\join.py", line 363, in join
    return join_aux(source_name, source_key, source_delete, target_name, target_key, fields, full, mode)
  File "C:\Users\midhu\Documents\midhun\covid 19 projects\envs\covid19_1_env\lib\site-packages\dataflows\processors\join.py", line 172, in join_aux
    db_keys_usage = KVFile()
  File "C:\Users\midhu\Documents\midhun\covid 19 projects\envs\covid19_1_env\lib\site-packages\kvfile\kvfile.py", line 19, in __init__
    self.db = DB_ENGINE.connect(self.tmpfile.name)
sqlite3.OperationalError: unable to open database file

**Comment by anuveyatsu** [comment] 2020-03-26 13:23
I can confirm that this is windows specific issue. Here is the tracker - https://github.com/datahq/dataflows/issues/57

**Comment by anuveyatsu** [comment] 2020-04-04 07:03
Closing this as WONTFIX

**Closed by anuveyatsu** 2020-04-04 07:03 UTC
Labels: wontfix
