### ISSUE TITLE
Canada Recovery Data

### ISSUE THREAD

**Issue by RKattoula** [datasets/covid-19#47] opened 2020-03-29 00:57 UTC
Not seeing recovery data for Canada, but it is being updated in the John Hopkins data. 

Those are the only NA's I'm seeing. Great work on this - thanks a ton.

**Comment by anuveyatsu** [comment] 2020-03-29 03:58
@RKattoula thanks for reporting this. It's happening due to inconsistency in the data files from the upstream:

* look at the confirmed (and deaths) data - https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv - you can see that Canada figures are provided by its region
* however, recovered data for Canada is provided in total for entire country - https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv - so we can't join that data with confirmed and deaths cases

Any suggestion would be useful 😄

**Comment by sgg70** [comment] 2020-03-29 05:00
Suggestions: There seem to be at least 3 options: (1) leave out to reflect the source and see if they will eventually update  (2) "allocate" the total # of Recovered to the various provinces (for example in relation to their confirmed cases) or (3) just push the Revovered cases for Canada into a new set of rows where the Province/Region is labelled as something non-existing like ***RECOVERED AGGREGATE*** and which then will just have the Recovered numbers.

(1) is obviously the easiest...
(2) is inventing numbers that don't really exist and may not be useful for some
(3) [my **preference**] at least on a sum-per-country level we are back to the full picture

**Comment by anuveyatsu** [comment] 2020-03-29 07:35
@sgg70 option 3 sounds good to me

**Comment by anuveyatsu** [comment] 2020-03-29 16:41
Fixed. Please, check and close this issue.

@RKattoula @sgg70

**Comment by sgg70** [comment] 2020-03-29 16:55
hmm... just one question:
![image](https://user-images.githubusercontent.com/61889932/77855123-acc29100-71ab-11ea-855f-88a9fef99c4e.png)
looking at the raw file, there is now a "Recovery" block with no real value, and then the "Recovery Aggregated", as suggested. I guess that first part can be omitted!?

**Comment by anuveyatsu** [comment] 2020-03-29 17:01
@sgg70 yes, the first one is the buggy data from the upstream that I've missed. Should be fixed now.

**Closed** 2020-03-29 17:47 UTC
