### ISSUE TITLE
google spreacsheet MAY have some new data sources

### ISSUE THREAD

**Issue by jottinger** [datasets/covid-19#9] opened 2020-03-14 16:49 UTC
https://docs.google.com/spreadsheets/d/1g_YxmDfQx7aOU2DKzNZo9b-NTk62Bju6X3z6OuCa6gw/htmlview?sle=true#gid=515684451

Need to look at the current data sources and these and compare. Just keeping track here.

**Comment by rufuspollock** [comment] 2020-03-22 19:16
@jottinger can you provide a bit more info on what new sources are there.

**Comment by anuveyatsu** [comment] 2020-04-04 07:04
Closing this as INVALID because we couldn't reproduce it.

**Closed by anuveyatsu** 2020-04-04 07:04 UTC
Labels: invalid
