### ISSUE TITLE
Delayed data - last update 4 days ago

### ISSUE THREAD

**Issue by snympi** [datasets/covid-19#91] opened 2020-08-23 23:06 UTC
I've been using the data for months now and accustomed to the 2-day delay. It seems that updates stopped at 18 May's data. Could you please confirm or update?

**Comment by anuveyatsu** [comment] 2020-08-24 05:01
hey @snympi thanks for reporting. I can confirm that we are working on fixing this so it will be updated ASAP.

**Comment by snympi** [comment] 2020-08-25 03:09
@anuveyatsu thanks for confirming. Any ETA on the fix?

**Comment by lordruzi** [comment] 2020-08-26 11:56
Hi everyone,
Any update on this?

**Comment by mattlgardner** [comment] 2020-08-27 15:03
Hi all - Guessing still no change on the missing data?

**Comment by raniermc** [comment] 2020-08-31 02:33
Hey, this project it's over?

**Comment by olwal** [comment] 2020-08-31 04:36
Same here, any plans on bringing back the up-to-date data? 
Would be good to know because I would really like to avoid having to migrate to a different data source. 
I really appreciated your work and how easy it was to integrate this w/ for example the population datasets. 

Either way, thanks for your great work!

**Comment by sdangt** [comment] 2020-08-31 12:45
This is really too bad.  I think a lot of people were using this data, which was presented in a nice clean format.  It would just be helpful to know in advance if a project is going to stop.  I incorporated this into my spreadsheet analysis, but the data here is now nearly two weeks out of date, and there are no updates about it, so it seems like people just disappeared into the night.  Thanks for the effort initially.  No one knew for sure how long this pandemic would go, but I think it was clear that it would probably still be troublesome at this point, and it probably will be into next year as well.  So data needs to go at least through that period if it is to be most useful.

**Comment by Morisset** [comment] 2020-08-31 19:56
It is possible to generate the tables locally on your own computer by running the following script:
https://raw.githubusercontent.com/datasets/covid-19/master/scripts/process.py 
I did a fork of the repository and run the process script in it, then commit the new files, so on my fork the data are uptodate. I will try to run it everyday.
My fork is there: https://github.com/Morisset/covid-19

**Comment by sglavoie** [comment] 2020-08-31 20:51
Thank you @Morisset for sharing this information with others and for hosting a backup of the latest data :+1:. This is indeed a viable solution while we are working on a fix. I have updated the data manually in this repo for now in https://github.com/datasets/covid-19/commit/3497aad30f6d1da1e501a9b43fb01635ae5e2466.

**Comment by Morisset** [comment] 2020-08-31 20:54
Great @sglavoie ! How do we proceed now? Do I update the data manually on my fork everyday, or will you do it?

**Comment by sglavoie** [comment] 2020-08-31 20:59
If you would like to give us a hand with this while we get to provide a more permanent solution on our side, that would be quite useful! You might want to send a daily pull request while we get this in order so you are recognized as a valuable contributor in the process and we can all enjoy up-to-date data :wink:.

**Comment by Morisset** [comment] 2020-08-31 21:04
OK, I'll try to do it. It seems the update of the original data from CSSEGISandData may appear a little late for me (22h PDT time), I'll do my best. I run the process script, commit the new files and ask for a pull request (or can you update from my fork without a pull request? I'm not sure how to put the request in a shell script call from crontab...)

**Comment by sglavoie** [comment] 2020-08-31 21:19
@Morisset: [this could be useful](https://stackoverflow.com/questions/4414140/git-auto-pull-using-cronjob) for the PR. If not, don't hesitate to let us know when you're updating. Else, I will have a look and merge the changes a bit later. In any case, thanks for your helping hand! Hopefully we'll get things in order soon enough :wink:.

**Comment by Morisset** [comment] 2020-08-31 23:13
OK, I'll have the following script running every midnight PDT:
`#!/bin/tcsh
set TODAY=`date +"%m-%d-%y"`
cd /home/morisset/covid-19
python scripts/process.py
git commit -a -m "Update $TODAY"
git push
hub pull-request -m "Test command line"  -b datasets:master -h Morisset:master 
`
I just ran it, data are note updated, but one json file was. The script run correctly, a request have been sent, let's see tonight if OK from crontab.

**Comment by jochym** [comment] 2020-09-01 08:02
@sglavoie Let me ask: why the procedure takes so long? Can we do something out that? Can I help in some way? Maybe we should rethink the algorithm - otherwise I think that this may be unsustainable i the coming months (this thing is not going away soon, sedly).

**Comment by sglavoie** [comment] 2020-09-01 12:47
@Morisset: Thank you, changes merged! However, could you manually pull the updates before your script runs again so we are in sync and can merge cleanly? That would be great. Thanks for helping by the way :wink:.

@jochym: we haven't been able to work on the issue so far, but thankfully we'll start bringing a fix really soon, don't you worry! :smile: We will keep the data updated for now with the kind help from @Morisset, which is mostly an automated process. The script is being run off the same code we have and produces the expected output, but we will optimize the code so it doesn't take so long to get the changes in. A partial fix already exists using a different library (Pandas): I will let you know once it's done and we have QA the results before making those changes to the repo. :+1:

**Comment by sglavoie** [comment] 2020-09-07 15:35
**FIXED**: Since commit c5b86f83f30c81ca2f814c3afc1ca720ed3edd50 from 3 days ago, the data has been successfully updating on GitHub. Closing this issue as nothing else needs to be done for now with the code itself.

Note: There is a problem regarding the deployment to DataHub, but this is unrelated to the data itself, which is correctly being updated here.

**Closed by sglavoie** 2020-09-07 15:35 UTC
