### ISSUE TITLE
Delayed data updates

### ISSUE THREAD

**Issue by soham-98** [datasets/covid-19#92] opened 2020-08-24 03:14 UTC
This is one of the reliable sources for us to track COVID-19 progression and we've been using the data for quite some time. We noticed that the data has not been updated after the 18th of August. Could you please confirm or update?

**Comment by anuveyatsu** [comment] 2020-08-24 05:03
Hey @soham-98 yes, we're working on that. Closing this issue as duplicate of #91

**Closed by anuveyatsu** 2020-08-24 05:03 UTC
