### ISSUE TITLE
Data is wrong

### ISSUE THREAD

**Issue by alaa137** [datasets/covid-19#3] opened 2020-03-09 07:29 UTC
These numbers are wrong. Where is this data taken from? Compare with https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6

**Comment by cpetrocheilos** [comment] 2020-03-09 18:50
The data is not wrong.Simply the data are a cumsum from each county and city and the current date gives you the current number of observation for confirmed etc

**Comment by sciencemike** [comment] 2020-03-09 22:30
Um no.  The data is wrong.   Look at Italy for example or Korea.  If you sum the numbers you get 1290 cases for korea up to 3/6/2020.  The number reported is many thousands higher than that.   Look at italy also, same problem.   If you sum all of the infected numbers you only get 1292 cases as of 3/6/2020.   Please dont just say @alaa137 is wrong.   PLEASE JUST ADD THE NUMBERS UP YOURSELF.  1290 does not equal 6000++ or 1292 does not equal >8000.   Please no disrespect intended.  I just want correct data, and i like the way you populated the dataframe.

**Comment by cpetrocheilos** [comment] 2020-03-09 23:40
You are right I thought I was by a mistake on another repository 😋😋 try Johns Hopkins CSSE repository the data was good!

**Comment by zelima** [comment] 2020-03-10 05:52
Thanks for reporting looking into it

**Comment by zelima** [comment] 2020-03-10 05:53
Updated, numbers should look better... Please confirm and close

data is coming from https://github.com/CSSEGISandData/COVID-19 unpivoted and normalized a bit.

**Comment by zelima** [comment] 2020-03-18 06:04
Think we can close this now. Please reopen if you find data wrong

**Closed by zelima** 2020-03-18 06:04 UTC
